input_bounds =  [];
input_bounds.('produced_gas_molarflow') = [250, 450];
input_bounds.('produced_gas_dev_ethane') = [-0.025, 0.025];
input_bounds.('produced_gas_dev_propane') = [-0.025, 0.025]; 
input_bounds.('demethanizer_reflux_ratio') = [0.75, 6.0];
input_bounds.('deethaner_reflux_ratio') = [0.75, 6.0];
input_bounds.('debutanizer_reflux_ratio') = [0.75, 6.0];
input_bounds.('demethanizer_reboiler_temp') = [245, 260];
input_bounds.('deethaner_reboiler_temp') = [295, 325];
input_bounds.('debutanizer_reboiler_temp') = [350, 365];
input_bounds.('demethanizer_pressure') = [1.0e6, 1300000];
input_bounds.('deethaner_pressure') = [650000, 1050000];
input_bounds.('debutanizer_pressure') = [450000, 550000];

% random inference, replace with desired inputs
x = zeros(13,1);
x(1) = rand()*(input_bounds.produced_gas_molarflow(2) - input_bounds.produced_gas_molarflow(1)) + input_bounds.produced_gas_molarflow(1);
x(3) = 0.0872501 + rand()*(input_bounds.produced_gas_dev_ethane(2) - input_bounds.produced_gas_dev_ethane(1)) + input_bounds.produced_gas_dev_ethane(1);
x(4) = 0.0523501 + rand()*(input_bounds.produced_gas_dev_propane(2) - input_bounds.produced_gas_dev_propane(1)) + input_bounds.produced_gas_dev_propane(1);
x(2) = 0.8376- x(3)- x(4);
x(5) = rand()*(input_bounds.demethanizer_reflux_ratio(2) - input_bounds.demethanizer_reflux_ratio(1)) + input_bounds.demethanizer_reflux_ratio(1);
x(6) = rand()*(input_bounds.deethaner_reflux_ratio(2) - input_bounds.deethaner_reflux_ratio(1)) + input_bounds.deethaner_reflux_ratio(1);
x(7) = rand()*(input_bounds.debutanizer_reflux_ratio(2) - input_bounds.debutanizer_reflux_ratio(1)) + input_bounds.debutanizer_reflux_ratio(1);
x(8) = rand()*(input_bounds.demethanizer_reboiler_temp(2) - input_bounds.demethanizer_reboiler_temp(1)) + input_bounds.demethanizer_reboiler_temp(1);
x(9) = rand()*(input_bounds.deethaner_reboiler_temp(2) - input_bounds.deethaner_reboiler_temp(1)) + input_bounds.deethaner_reboiler_temp(1);
x(10) = rand()*(input_bounds.debutanizer_reboiler_temp(2) - input_bounds.debutanizer_reboiler_temp(1)) + input_bounds.debutanizer_reboiler_temp(1);
x(11) = rand()*(input_bounds.demethanizer_pressure(2) - input_bounds.demethanizer_pressure(1)) + input_bounds.demethanizer_pressure(1);
x(12) = rand()*(input_bounds.deethaner_pressure(2) - input_bounds.deethaner_pressure(1)) + input_bounds.deethaner_pressure(1);
x(13) = rand()*(input_bounds.debutanizer_pressure(2) - input_bounds.debutanizer_pressure(1)) + input_bounds.debutanizer_pressure(1);

load('naturalGasProcessingUnit_model.mat')
[output_values] = example3_inference(x,naturalGasProcessingUnit_mlp);

output_names = [
"Bottom1CarbonDioxideMolarFraction",...
"Bottom1EthaneMolarFraction",...
"Bottom1IsobutaneMolarFraction",...
"Bottom1IsopentaneMolarFraction",...
"Bottom1MethaneMolarFraction",...
"Bottom1MolarFlow",...
"Bottom1NButaneMolarFraction",...
"Bottom1NPentaneMolarFraction",...
"Bottom1PropaneMolarFraction",...
"Bottom2CarbonDioxideMolarFraction",...
"Bottom2EthaneMolarFraction",...
"Bottom2IsobutaneMolarFraction",...
"Bottom2IsopentaneMolarFraction",...
"Bottom2MolarFlow",...
"Bottom2NButaneMolarFraction",...
"Bottom2NPentaneMolarFraction",...
"Bottom2PropaneMolarFraction",...
"Column1CondenserDuty",...
"Column2CondenserDuty",...
"Column3CondenserDuty",...
"CompressorDuty",...
"CoolerDuty",...
"ExpanderDuty",...
"HeaterDuty",...
"LiquidMolarFlow",...
"Product1MethaneMolarFraction",...
"Product1MolarFlow",...
"Product1NitrogenMolarFraction",...
"Product2CarbonDioxideMolarFraction",...
"Product2EthaneMolarFraction",...
"Product2IsobutaneMolarFraction",...
"Product2MethaneMolarFraction",...
"Product2MolarFlow",...
"Product2NButaneMolarFraction",...
"Product2PropaneMolarFraction",...
"Product3CarbonDioxideMolarFraction",...
"Product3EthaneMolarFraction",...
"Product3IsobutaneMolarFraction",...
"Product3IsopentaneMolarFraction",...
"Product3MolarFlow",...
"Product3NButaneMolarFraction",...
"Product3NPentaneMolarFraction",...
"Product3PropaneMolarFraction",...
"Product4IsobutaneMolarFraction",...
"Product4IsopentaneMolarFraction",...
"Product4MolarFlow",...
"Product4NButaneMolarFraction",...
"Product4NPentaneMolarFraction",...
"Product4PropaneMolarFraction",...
"Column1ReboilerDuty",...
"Column2ReboilerDuty",...
"Column3ReboilerDuty",...
];


 out = [];
for idx = 1:length(output_values)
    out.(output_names(idx)) = output_values(idx);
end
out