addpath("../Surrogate Model")
addpath("../Data")
load('naturalGasProcessingUnit_model.mat')

xtest = readtable('..\Data\test_Inputs.csv');
ytest = readtable('..\Data\test_Outputs.csv');
xtest = table2array(xtest);
ytest = table2array(ytest);
ypred_test = example3_inference(xtest',naturalGasProcessingUnit_mlp);
error_test = abs(ytest-ypred_test);
test_mean = mean(error_test);
test_std = std(error_test);

xvald = readtable('..\Data\vald_Inputs.csv');
yvald = readtable('..\Data\vald_Outputs.csv');
xvald = table2array(xvald);
yvald = table2array(yvald);
ypred_vald = example3_inference(xvald',naturalGasProcessingUnit_mlp);
error_vald = abs(yvald-ypred_vald);
vald_mean = mean(error_vald);
vald_std = std(error_vald);

xtrain = readtable('..\Data\train_Inputs.csv');
ytrain = readtable('..\Data\train_Outputs.csv');
xtrain = table2array(xtrain);
ytrain = table2array(ytrain);
ypred_train = example3_inference(xtrain',naturalGasProcessingUnit_mlp);
error_train = abs(ytrain-ypred_train);
train_mean = mean(error_train);
train_std = std(error_train);


% no_change_output_names = [
% "product3_methane_frac",...
% "product3_n2_frac",...
% "product4_c02_frac",...
% "product4_ethane_frac",...
% "product4_methane_frac",...
% "product4_n2_frac",...
% "bottom2_methane_frac",...
% "bottom2_n2_frac",...
% "product2_n2_frac",...
% "bottom1_n2_frac",...
% "product1_propane_frac",...
% "product1_npentane_frac",...
% "product1_isopentane_frac",...
% "product1_nbutane_frac",... 
% "product1_isobutane_frac",...
% "product2_isopentane_frac",...
% "product2_npentane_frac",...
% "product1_ethane_frac",...
% "product1_c02_frac",...
% ];

output_names = [
"Bottom 1 Carbon Dioxide Molar Fraction",...
"Bottom 1 Ethane Molar Fraction",...
"Bottom 1 Isobutane Molar Fraction",...
"Bottom 1 Isopentane Molar Fraction",...
"Bottom 1 Methane Molar Fraction",...
"Bottom 1 Molar Flow",...
"Bottom 1 N-Butane Molar Fraction",...
"Bottom 1 N-Pentane Molar Fraction",...
"Bottom 1 Propane Molar Fraction",...
"Bottom 2 Carbon Dioxide Molar Fraction",...
"Bottom 2 Ethane Molar Fraction",...
"Bottom 2 Isobutane Molar Fraction",...
"Bottom 2 Isopentane Molar Fraction",...
"Bottom 2 Molar Flow",...
"Bottom 2 N-Butane Molar Fraction",...
"Bottom 2 N-Pentane Molar Fraction",...
"Bottom 2 Propane Molar Fraction",...
"Column 1 Condenser Duty",...
"Column 2 Condenser Duty",...
"Column 3 Condenser Duty",...
"Compressor Duty",...
"Cooler Duty",...
"Expander Duty",...
"Heater Duty",...
"Liquid Molar Flow",...
"Product 1 Methane Molar Fraction",...
"Product 1 Molar Flow",...
"Product 1 Nitrogen Molar Fraction",...
"Product 2 Carbon Dioxide Molar Fraction",...
"Product 2 Ethane Molar Fraction",...
"Product 2 Isobutane Molar Fraction",...
"Product 2 Methane Molar Fraction",...
"Product 2 Molar Flow",...
"Product 2 N-Butane Molar Fraction",...
"Product 2 Propane Molar Fraction",...
"Product 3 Carbon Dioxide Molar Fraction",...
"Product 3 Ethane Molar Fraction",...
"Product 3 Isobutane Molar Fraction",...
"Product 3 Isopentane Molar Fraction",...
"Product 3 Molar Flow",...
"Product 3 N-Butane Molar Fraction",...
"Product 3 N-Pentane Molar Fraction",...
"Product 3 Propane Molar Fraction",...
"Product 4 Isobutane Molar Fraction",...
"Product 4 Isopentane Molar Fraction",...
"Product 4 Molar Flow",...
"Product 4 N-Butane Molar Fraction",...
"Product 4 N-Pentane Molar Fraction",...
"Product 4 Propane Molar Fraction",...
"Column 1 Reboiler Duty",...
"Column 2 Reboiler Duty",...
"Column 3 Reboiler Duty",...
 ];

output_units = ["-","-","-","-","-",...
            "mol/s",...    
            "-","-","-","-","-","-","-",...
            "mol/s",...
            "-","-","-",...
            "kW","kW","kW","kW","kW","kW","kW",...
            "mol/s",...
            "-",...
            "mol/s",...
            "-","-","-","-","-",...
            "mol/s",...
            "-","-","-","-","-","-",...
            "mol/s",...
            "-","-","-","-","-",...
            "mol/s",...
            "-","-","-",...
            "kW","kW","kW"];

% create figures
for idx = 1:numel(output_names)
    fig = figure;
    set(gcf,'position',[1 49 1536 836.8000])
    hold on
    % customize the plot as needed
    title(strcat("Example 3: ", output_names(idx), " Predictions"),'FontSize',18);
    ylabel(strcat("Physics-Based ", output_names(idx)," (",output_units(idx),")"),'FontSize',18);
    xlabel(strcat("Surrogate Model ", output_names(idx)," (",output_units(idx),")"),'FontSize',18);
    scatter(ytrain(:,idx),ypred_train(:,idx), 7, 'k', 'filled')
    scatter(yvald(:,idx),ypred_vald(:,idx), 7, 'b', 'filled')
    scatter(ytest(:,idx),ypred_test(:,idx), 7, 'r', 'filled')
    ylim_ = ylim;
    plot([ylim_(1),ylim_(2)],[ylim_(1),ylim_(2)],'k--')
    axis tight
    legend(strcat("Train (error mean = ", num2str(train_mean(idx),'%.2e'), " (", output_units(idx), "), error std = ", num2str(train_std(idx),'%.2e')," (", output_units(idx), "))"),...
        strcat("Validate (error mean = ", num2str(vald_mean(idx),'%.2e'), " (", output_units(idx), "), error std = ", num2str(vald_std(idx),'%.2e')," (", output_units(idx), "))"),......
        strcat("Test (error mean = ", num2str(test_mean(idx),'%.2e'), " (", output_units(idx), "), error std = ", num2str(test_std(idx),'%.2e')," (", output_units(idx), "))"),......
        ['Perfect Prediction Reference, x=y'],...
        'FontSize',18,'Location','NorthWest');
    hAx = gca;
    hAx.XAxis.FontSize = 18;
    hAx.YAxis.FontSize = 18;
    grid on
    box on
    filename = strcat('Example3_',strrep(output_names(idx),' ',''),'_truthplot');
    saveas(gcf,strcat(filename,'.fig'))
    saveas(gcf,strcat(filename,'.png'))
end

column_names = ["Mean Error", "Std. Error","Sampled Mean","Sampled Max"];
data = [test_mean',test_std', mean(abs(ytest))',max(abs(ytest))'];
table = array2table(double(data),'VariableNames',column_names);
table.("Output") = output_names';
table.("Units") = output_units';
table = [table(:,end-1) table(:,end) table(:,1:end-2)];
reorderIdx = [18,50,19,51,20,52,21,22,23,24,27,26,28,6,5,2,7,1,8,4,3,9,...
                33,32,30,34,36,31,35,14,11,15,10,16,13,12,17,...
                40,37,41,36,42,39,38,43,...
                46,47,48,45,44,49,...
                25
                ];
table = table(reorderIdx,:);
writetable(table, 'resultsTable.csv');

rawData = readtable('..\Data\raw_Data.csv');
dwsim_time = mean(rawData.dwsim_time(~isnan(rawData.dwsim_time)));

lower_bounds = [250,0.6979997-0.05,0.0872501-0.025,0.0523501-0.025,0.75,0.75,0.75,245,295,350,1.0e6,650000,450000];
upper_bounds = [450,0.6979997+0.05,0.0872501+0.025,0.0523501+0.025,6,6,6,260,325,365,1300000,1050000,550000];
randomInputs = rand(10000,13).*(upper_bounds - lower_bounds) + lower_bounds;
randomInputs(:,2) = 0.8376 - randomInputs(:,4) - randomInputs(:,3);
tic;
for idx = 1:10000
    example3_inference(randomInputs(idx,:)',naturalGasProcessingUnit_mlp);
end
surrogate_single_eval = toc/10000;

lower_bounds = [250,0.6979997-0.05,0.0872501-0.025,0.0523501-0.025,0.75,0.75,0.75,245,295,350,1.0e6,650000,450000];
upper_bounds = [450,0.6979997+0.05,0.0872501+0.025,0.0523501+0.025,6,6,6,260,325,365,1300000,1050000,550000];
randomInputs = rand(100000,13).*(upper_bounds - lower_bounds) + lower_bounds;
randomInputs(:,2) = 0.8376 - randomInputs(:,4)- randomInputs(:,3);
tic;
for idx = 0:99
    example3_inference(randomInputs(1+idx*1000:(1+idx)*1000,:)',naturalGasProcessingUnit_mlp);
end
surrogate_batch_eval = toc/100;

column_names = ["DWSIM time", "Surrogate Single Eval","Surrogate Batch Eval"];
data = [dwsim_time,surrogate_single_eval, surrogate_batch_eval];
table = array2table(double(data),'VariableNames',column_names);
writetable(table, 'timingTable.csv');