clear all
close all
addpath('Sample Comparison\')
addpath('DWSIM Files\')

modelName = 'DWSIM';

inputSamplingNames = ["feed_pressure","feed_molarflow","n_hexane_isopentane_dev","rebolier_temp","reflux_ratio","top_pressure"];


inputBounds = struct(...
                    'feed_pressure', [175000, 225000], ...
                    'feed_molarflow', [1250, 2500], ...
                    'n_hexane_isopentane_dev', [-0.15, 0.15], ...
                    'rebolier_temp', [350, 375], ...
                    'reflux_ratio', [1.0, 3.0], ...
                    'top_pressure', [180000, 260000] ...
                );

modelSamplingNames = ["feed_pressure", "feed_molarflow", "feed_propane", "feed_isobutane",...
                    "feed_n_hexane", "feed_isopentane", "feed_n_heptane", "rebolier_temp",...
                    "reflux_ratio", "top_pressure", "top_molar_flow", "top_propane",...
                    "top_isobutane", "top_n_hexane", "top_isopentane", "top_n_heptane",...
                    "bottom_molar_flow", "bottom_propane", "bottom_isobutane", "bottom_n_hexane",...
                    "bottom_isopentane", "bottom_n_heptane", "cduty", "rduty",...
                    "dwsim_time", "solved"];

inputSurrogateNames = ["feed_pressure",...
                    "feed_molarflow",...
                    "feed_n_hexane",...
                    "feed_isopentane",...
                    "rebolier_temp",...
                    "reflux_ratio",...
                    "top_pressure"];

outputSurrogateNames = [ "bottom_propane",...
                    "bottom_isobutane", "bottom_n_hexane",...
                    "bottom_isopentane", "bottom_n_heptane", "bottom_molar_flow"];

function xs = inputScalingFunction(inputBounds, x)
    xs = x;
    xs(:, 1) = x(:, 1) * (inputBounds.feed_pressure(2) - inputBounds.feed_pressure(1)) + inputBounds.feed_pressure(1);
    xs(:, 2) = x(:, 2) * (inputBounds.feed_molarflow(2) - inputBounds.feed_molarflow(1)) + inputBounds.feed_molarflow(1);
    xs(:, 3) = 0.46 + ( x(:, 3) * (inputBounds.n_hexane_isopentane_dev(2) - inputBounds.n_hexane_isopentane_dev(1)) + inputBounds.n_hexane_isopentane_dev(1) );
    xs(:, 4) = 0.30 - ( x(:, 3) * (inputBounds.n_hexane_isopentane_dev(2) - inputBounds.n_hexane_isopentane_dev(1)) + inputBounds.n_hexane_isopentane_dev(1) );
    xs(:, 5) = x(:, 4) * (inputBounds.rebolier_temp(2) - inputBounds.rebolier_temp(1)) + inputBounds.rebolier_temp(1);
    xs(:, 6) = x(:, 5) * (inputBounds.reflux_ratio(2) - inputBounds.reflux_ratio(1)) + inputBounds.reflux_ratio(1);
    xs(:, 7) = x(:, 6) * (inputBounds.top_pressure(2) - inputBounds.top_pressure(1)) + inputBounds.top_pressure(1);
end

function modelSampler(inputBounds, inputCSV, outputCSV, inputNames, modelSamplingNames)
    disp(inputCSV)
    disp(outputCSV)
    pyrun("import DWSIM_Sampler")
    while py.DWSIM_Sampler.Sampler(inputBounds, outputCSV, inputCSV)
        numRows = height(readtable(inputCSV));
        disp(['There are ', num2str(numRows), ' samples remaining.']);
    end
end

runSamplingComparison(modelName,...
                    inputSamplingNames,...
                    modelSamplingNames,...
                    inputSurrogateNames,...
                    outputSurrogateNames,...
                    @(x,y,w,v) modelSampler(inputBounds, x, y, w, v),...
                    @(x) inputScalingFunction(inputBounds, x),...
                    'increaseSizeTraining', 150,...
                    'increaseSizeValidate', 30,...
                    'initialSizeMultiple', 2,...
                    'minMiniBatchSize', 150,...
                    'numRounds', 25,...
                    'scalePredictTesting', true,...
                    'skipRandom', true,...
                    'skipWarmStartSobol', true);