input_bounds =  [];
input_bounds.('feed_molarflow') = [20, 35]; 
input_bounds.('ethanol_to_benzene') = [0.4,0.6];
input_bounds.('makeup_molarflow') = [0.05, 0.12]; 
input_bounds.('column1_refluxratio') = [1.5, 2.5];
input_bounds.('column1_reboiler_temp') = [385,395];
input_bounds.('column2_refluxratio') = [5.0, 7.0];
input_bounds.('column2_reboiler_temp') = [395, 410];
input_bounds.('cooler_outlettemp') = [315, 340];

% random inference, replace with desired inputs
x = zeros(7,1);
x(1) = rand()*(input_bounds.feed_molarflow(2) - input_bounds.feed_molarflow(1)) + input_bounds.feed_molarflow(1);
x(2) = rand()*(input_bounds.ethanol_to_benzene(2) - input_bounds.ethanol_to_benzene(1)) + input_bounds.ethanol_to_benzene(1);  
x(3) = 1.0 - x(2);
x(4) = rand()*(input_bounds.makeup_molarflow(2) - input_bounds.makeup_molarflow(1)) + input_bounds.makeup_molarflow(1);
x(5) = rand()*(input_bounds.column1_refluxratio(2) - input_bounds.column1_refluxratio(1)) + input_bounds.column1_refluxratio(1);
x(6) = rand()*(input_bounds.column1_reboiler_temp(2) - input_bounds.column1_reboiler_temp(1)) + input_bounds.column1_reboiler_temp(1);
x(7) = rand()*(input_bounds.column2_refluxratio(2) - input_bounds.column2_refluxratio(1)) + input_bounds.column2_refluxratio(1);
x(8) = rand()*(input_bounds.column2_reboiler_temp(2) - input_bounds.column2_reboiler_temp(1)) + input_bounds.column2_reboiler_temp(1);
x(9) = rand()*(input_bounds.cooler_outlettemp(2) - input_bounds.cooler_outlettemp(1)) + input_bounds.cooler_outlettemp(1);


load('extractiveDistillation_model.mat')
[output_values] = example2_inference(x,extractiveDistillation_mlp);

output_names = [
"column1_condenser_duty",...
"column1_reboiler_duty",...
"column2_condenser_duty",...
"column2_reboiler_duty",...
"cooler_duty",...
"top1_molarflow",...
"top1_benzene_frac",...
"top1_ethanol_frac",...
"top1_pxylene_frac",...
"top2_molarflow",...
"top2_benzene_frac",...
"top2_ethanol_frac",...
"top2_pxylene_frac",...
"bottom1_molarflow",...
"bottom1_benzene_frac",...
"bottom1_ethanol_frac",...
"bottom1_pxylene_frac",...
"bottom2_molarflow",...
"bottom2_benzene_frac",...
"bottom2_pxylene_frac",...
'recycle_stream_molar_flow',...
'recycle_stream_benzene_frac',...
'recycle_stream_pxylene_mole_frac'
];

out = [];
for idx = 1:length(output_values)
    out.(output_names(idx)) = output_values(idx);
end
out